# Site settings
title: 일곱번째 손님
email: the7sign@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Language - PHP, ASP, C#, JAVA, JavaScript <br>
  Tools - VisualStudio, AndroidStudio, PHPStorm, IntelliJ <br>
  DB - SQL-Server, MariaDB/MySQL, Redis <br>
  ETC - HAProxy, JQuery <br>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://the7sign.github.io/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  the7sign

# Build settings
markdown: kramdown

highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'


paginate: 4

author: the7sign

gems: [jekyll-paginate, jekyll-seo-tag]
