# Site settings
title: 일곱번째 손님
email: the7sign@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://the7sign.github.io/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  the7sign

# Build settings
markdown: kramdown

paginate: 4

author: the7sign

gems: [jekyll-paginate]
